export const BahamaStates =  [
    { value: "AK", label: "Acklins" },
    { value: "AC", label: "Acklins and Crooked Islands" },
    { value: "BY", label: "Berry Islands" },
    { value: "BI", label: "Bimini" },
    { value: "BP", label: "Black Point" },
    { value: "CI", label: "Cat Island" },
    { value: "CO", label: "Central Abaco" },
    { value: "CS", label: "Central Andros" },
    { value: "CE", label: "Central Eleuthera" },
    { value: "CK", label: "Crooked Island" },
    { value: "EG", label: "East Grand Bahama" },
    { value: "EX", label: "Exuma" },
    { value: "FP", label: "Freeport" },
    { value: "FC", label: "Fresh Creek" },
    { value: "GH", label: "Governor's Harbour" },
    { value: "GC", label: "Grand Cay" },
    { value: "GT", label: "Green Turtle Cay" },
    { value: "HI", label: "Harbour Island" },
    { value: "HR", label: "High Rock" },
    { value: "HT", label: "Hope Town" },
    { value: "IN", label: "Inagua" },
    { value: "KB", label: "Kemps Bay" },
    { value: "LI", label: "Long Island" },
    { value: "MC", label: "Mangrove Cay" },
    { value: "MH", label: "Marsh Harbour" },
    { value: "MG", label: "Mayaguana District" },
    { value: "NP", label: "New Providence" },
    { value: "NB", label: "Nichollstown and Berry Islands" },
    { value: "NO", label: "North Abaco" },
    { value: "NS", label: "North Andros" },
    { value: "NE", label: "North Eleuthera" },
    { value: "RI", label: "Ragged Island" },
    { value: "RS", label: "Rock Sound" },
    { value: "RC", label: "Rum Cay District" },
    { value: "SR", label: "San Salvador and Rum Cay" },
    { value: "SS", label: "San Salvador Island" },
    { value: "SP", label: "Sandy Point" },
    { value: "SO", label: "South Abaco" },
    { value: "SA", label: "South Andros" },
    { value: "SE", label: "South Eleuthera" },
    { value: "SW", label: "Spanish Wells" },
    { value: "WG", label: "West Grand Bahama" }
];
