export const USStates =  [
    { value: "AL", label: "Alabama" },
    { value: "AK", label: "Alaska" },
    { value: "AS", label: "American Samoa" },
    { value: "AZ", label: "Arizona" },
    { value: "AR", label: "Arkansas" },
    { value: "CA", label: "California" },
    { value: "CO", label: "Colorado" },
    { value: "CT", label: "Connecticut" },
    { value: "DE", label: "Delaware" },
    { value: "DC", label: "District of Columbia" },
    { value: "FL", label: "Florida" },
    { value: "GA", label: "Georgia" },
    { value: "GU", label: "Guam" },
    { value: "HI", label: "Hawaii" },
    { value: "ID", label: "Idaho" },
    { value: "IL", label: "Illinois" },
    { value: "IN", label: "Indiana" },
    { value: "IA", label: "Iowa" },
    { value: "KS", label: "Kansas" },
    { value: "KY", label: "Kentucky" },
    { value: "LA", label: "Louisiana" },
    { value: "ME", label: "Maine" },
    { value: "MD", label: "Maryland" },
    { value: "MA", label: "Massachusetts" },
    { value: "MI", label: "Michigan" },
    { value: "MN", label: "Minnesota" },
    { value: "MS", label: "Mississippi" },
    { value: "MO", label: "Missouri" },
    { value: "MT", label: "Montana" },
    { value: "NE", label: "Nebraska" },
    { value: "NV", label: "Nevada" },
    { value: "NH", label: "New Hampshire" },
    { value: "NJ", label: "New Jersey" },
    { value: "NM", label: "New Mexico" },
    { value: "NY", label: "New York" },
    { value: "NC", label: "North Carolina" },
    { value: "ND", label: "North Dakota" },
    { value: "MP", label: "Northern Mariana Islands" },
    { value: "OH", label: "Ohio" },
    { value: "OK", label: "Oklahoma" },
    { value: "OR", label: "Oregon" },
    { value: "PA", label: "Pennsylvania" },
    { value: "PR", label: "Puerto Rico" },
    { value: "RI", label: "Rhode Island" },
    { value: "SC", label: "South Carolina" },
    { value: "SD", label: "South Dakota" },
    { value: "TN", label: "Tennessee" },
    { value: "TX", label: "Texas" },
    { value: "UM", label: "United States Minor Outlying Islands" },
    { value: "VI", label: "United States Virgin Islands" },
    { value: "UT", label: "Utah" },
    { value: "VT", label: "Vermont" },
    { value: "VA", label: "Virginia" },
    { value: "WA", label: "Washington" },
    { value: "WV", label: "West Virginia" },
    { value: "WI", label: "Wisconsin" },
    { value: "WY", label: "Wyoming" }
];

export const MexicoStates = [
    { value: "AGU", label: "Aguascalientes" },
    { value: "BCN", label: "Baja California" },
    { value: "BCS", label: "Baja California Sur" },
    { value: "CAM", label: "Campeche" },
    { value: "CHP", label: "Chiapas" },
    { value: "CHH", label: "Chihuahua" },
    { value: "COA", label: "Coahuila" },
    { value: "COL", label: "Colima" },
    { value: "DUR", label: "Durango" },
    { value: "GUA", label: "Guanajuato" },
    { value: "GRO", label: "Guerrero" },
    { value: "HID", label: "Hidalgo" },
    { value: "JAL", label: "Jalisco" },
    { value: "MEX", label: "México" },
    { value: "CMX", label: "Mexico City" },
    { value: "MIC", label: "Michoacán" },
    { value: "MOR", label: "Morelos" },
    { value: "NAY", label: "Nayarit" },
    { value: "NLE", label: "Nuevo León" },
    { value: "OAX", label: "Oaxaca" },
    { value: "PUE", label: "Puebla" },
    { value: "QUE", label: "Querétaro" },
    { value: "ROO", label: "Quintana Roo" },
    { value: "SLP", label: "San Luis Potosí" },
    { value: "SIN", label: "Sinaloa" },
    { value: "SON", label: "Sonora" },
    { value: "TAB", label: "Tabasco" },
    { value: "TAM", label: "Tamaulipas" },
    { value: "TLA", label: "Tlaxcala" },
    { value: "VER", label: "Veracruz" },
    { value: "YUC", label: "Yucatán" },
    { value: "ZAC", label: "Zacatecas" }
];

export const CanadaProv = [
    { value: "AB", label: "Alberta" },
    { value: "BC", label: "British Columbia" },
    { value: "MB", label: "Manitoba" },
    { value: "NB", label: "New Brunswick" },
    { value: "NL", label: "Newfoundland and Labrador" },
    { value: "NT", label: "Northwest Territories" },
    { value: "NS", label: "Nova Scotia" },
    { value: "NU", label: "Nunavut" },
    { value: "ON", label: "Ontario" },
    { value: "PE", label: "Prince Edward Island" },
    { value: "QC", label: "Quebec" },
    { value: "SK", label: "Saskatchewan" },
    { value: "YT", label: "Yukon" }
];


export const BahamaStates =  [
    { value: "AK", label: "Acklins" },
    { value: "AC", label: "Acklins and Crooked Islands" },
    { value: "BY", label: "Berry Islands" },
    { value: "BI", label: "Bimini" },
    { value: "BP", label: "Black Point" },
    { value: "CI", label: "Cat Island" },
    { value: "CO", label: "Central Abaco" },
    { value: "CS", label: "Central Andros" },
    { value: "CE", label: "Central Eleuthera" },
    { value: "CK", label: "Crooked Island" },
    { value: "EG", label: "East Grand Bahama" },
    { value: "EX", label: "Exuma" },
    { value: "FP", label: "Freeport" },
    { value: "FC", label: "Fresh Creek" },
    { value: "GH", label: "Governor's Harbour" },
    { value: "GC", label: "Grand Cay" },
    { value: "GT", label: "Green Turtle Cay" },
    { value: "HI", label: "Harbour Island" },
    { value: "HR", label: "High Rock" },
    { value: "HT", label: "Hope Town" },
    { value: "IN", label: "Inagua" },
    { value: "KB", label: "Kemps Bay" },
    { value: "LI", label: "Long Island" },
    { value: "MC", label: "Mangrove Cay" },
    { value: "MH", label: "Marsh Harbour" },
    { value: "MG", label: "Mayaguana District" },
    { value: "NP", label: "New Providence" },
    { value: "NB", label: "Nichollstown and Berry Islands" },
    { value: "NO", label: "North Abaco" },
    { value: "NS", label: "North Andros" },
    { value: "NE", label: "North Eleuthera" },
    { value: "RI", label: "Ragged Island" },
    { value: "RS", label: "Rock Sound" },
    { value: "RC", label: "Rum Cay District" },
    { value: "SR", label: "San Salvador and Rum Cay" },
    { value: "SS", label: "San Salvador Island" },
    { value: "SP", label: "Sandy Point" },
    { value: "SO", label: "South Abaco" },
    { value: "SA", label: "South Andros" },
    { value: "SE", label: "South Eleuthera" },
    { value: "SW", label: "Spanish Wells" },
    { value: "WG", label: "West Grand Bahama" }
];
